# Generated by Django 5.2.6 on 2025-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zip',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
